# Generated by Django 5.0.3 on 2024-04-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selftask',
            options={'verbose_name': 'Мои задачи', 'verbose_name_plural': 'Мои задачи'},
        ),
    ]
